[package]
name = "Lodestone"
version = "0.1.0"
edition = "2021"

exclude = [
    "target/*",
    "InstanceTest/*"
]

[[bin]]
name = "test_ground"
path = "src/test_ground/main.rs"

[[bin]]
name = "main"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.5.13", features = ["headers", "ws"] }
futures = "0.3.21"
headers = "0.3"
tokio = { version = "1.0", features = ["full"] }
tokio-stream = "0.1"
tower-http = { version = "0.3.0", features = ["fs", "trace"] }# erased-serde = "0.3"
regex = "1.5.4"

serde_json = "1.0.82"
serde = { version = "1.0", features = ["derive"] }

reqwest = { version = "0.11.10", features = ["stream", "blocking"] }
futures-util = "0.3.14"
indicatif = "0.15.0"

fs_extra = "1.2.0"

uuid = "0.8.2"
sanitize-filename = "0.3.0"
rust-crypto = "^0.2"
# rocket_cors = "0.5.1"

sys-info = "0.9.1"
systemstat = "0.1.10"
rlua = "0.19.1"
rand = "0.6.5"
log = "0.4.17"
env_logger = "0.9.0"
zip = "0.6.2"
async-trait = "0.1.56"
