name: Cargo Check

on:
  workflow_dispatch:
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src-tauri

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        run: npm ci
      # - run: npm test

      - name: Build dashboard
        run: npm run build --if-present

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      - name: Cache Rust Dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
          prefix-key: rust-cache
          shared-key: ${{ runner.os }}-check
          key: 'v1'

      - name: Cargo Check
        run: cargo check --release
