name: client

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        working-directory: ./
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Rust toolchain 
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Cache Dependencies
      uses: Swatinem/rust-cache@v2
      with:
        key: ${{ runner.os }}-client

    - name: Build Backend
      run: cargo build --verbose --release
      
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Lodestone
        path: |
          ./target/release/Lodestone
          ./Rocket.toml
