name: client

on:
  push:
    branches:
      - main
      - releases/**
    
  pull_request:
    branches: 
      - main
      - releases/**

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        platform: [x86_64-unknown-linux-gnu, x86_64-pc-windows-gnu, aarch64-unknown-linux-gnu]

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.platform }}

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.platform }}-client

      - name: Build Backend
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.platform }}

      # on windows it's ./target/release/main.exe
      # on linux it's ./target/release/main

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platform }}-client${{ contains(matrix.platform, 'windows') && '.exe' || '' }}
          path: ./target/${{ matrix.platform }}/release/${{ contains(matrix.platform, 'windows') && 'main.exe' || 'main' }}
