name: lodestone-desktop
on:
  workflow_call:
    inputs:
      version:
        description: 'Version to tag release with'
        required: true
        default: 'edge'
        type: string

  workflow_dispatch:
    inputs:
      version:
        description: 'Version to tag release with'
        required: true
        default: 'edge'
        type: string

jobs:
  build-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      - name: Cache Rust Dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
          key: ${{ runner.os }}-tauri
          shared-key: ${{ runner.os }}-tauri-shared

      - name: Install npm dependencies
        run: npm ci

      - name: Build Tauri desktop app
        uses: tauri-apps/tauri-action@v0
        id: tauri

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
        with:
          tagName: ${{ inputs.version }}
          releaseName: 'Lodestone v__VERSION__'
          releaseBody: 'This is a prerelease version of Lodestone. Please report any bugs you find. Developers please modify this message to include a changelog before publishing.'
          includeUpdaterJson: true
          releaseDraft: true
          prerelease: true
      
      - name: Add windows portable exe to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./src-tauri/target/release/Lodestone.exe
          tag_name: ${{ inputs.version }}
          draft: true
          prerelease: true

      # on windows, cache installer in src-tauri/target/release/bundle/msi/Lodestone*.msi
      # on windows cache exe in src-tauri/target/release/Lodestone.exe
      # on linux, cache deb in src-tauri/target/release/bundle/deb/lodestone*.deb
      # on linux, cache appimage in src-tauri/target/release/bundle/appimage/lodestone*.AppImage
      # note linux has lowercase l, windows has uppercase L

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}-tauri
          path: |
            ${{steps.tauri.outputs.artifactPaths }}
            ./src-tauri/target/release/Lodestone.exe
# ./src-tauri/target/release/bundle/msi/Lodestone*.msi
# ./src-tauri/target/release/bundle/msi/Lodestone*.msi.zip
# ./src-tauri/target/release/bundle/msi/Lodestone*.msi.zip.sig
# ./src-tauri/target/release/bundle/deb/lodestone*.deb
# ./src-tauri/target/release/bundle/deb/lodestone*.deb.tar.gz
# ./src-tauri/target/release/bundle/deb/lodestone*.deb.tar.gz.sig
# ./src-tauri/target/release/bundle/appimage/lodestone*.AppImage
# ./src-tauri/target/release/bundle/appimage/lodestone*.AppImage.tar.gz
# ./src-tauri/target/release/bundle/appimage/lodestone*.AppImage.tar.gz.sig
# ./src-tauri/target/release/bundle/macos/Lodestone.app
# ./src-tauri/target/release/bundle/macos/Lodestone.app.tar.gz
# ./src-tauri/target/release/bundle/macos/Lodestone.app.tar.gz.sig
# ./src-tauri/target/release/bundle/macos/rw.Lodestone*.dmg
# ./src-tauri/target/release/bundle/macos/rw.Lodestone*.dmg.tar.gz
# ./src-tauri/target/release/bundle/macos/rw.Lodestone*.dmg.tar.gz.sig
