name: Build Lodestone Desktop
on:
  workflow_call:
    inputs:
      version:
        description: 'Version to tag release with'
        required: true
        default: 'edge'
        type: string
      debug:
        description: 'Whether to build in debug mode, uses less time but might run out of space on windows'
        required: true
        default: true
        type: boolean
      release:
        description: 'Whether to draft a release'
        required: true
        default: false
        type: boolean

  workflow_dispatch:
    inputs:
      version:
        description: 'Version to tag release with'
        required: true
        default: 'edge'
        type: string
      debug:
        description: 'Whether to build in debug mode, uses less time but might run out of space on windows'
        required: true
        default: true
        type: boolean
      release:
        description: 'Whether to draft a release'
        required: true
        default: false
        type: boolean

jobs:
  build-tauri:
    strategy:
      fail-fast: true
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      - name: Cache Rust Dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
          prefix-key: rust-cache
          shared-key: ${{ runner.os }}-tauri
          key: "v1"

      - name: Install npm dependencies
        run: npm ci

      - name: Build Tauri desktop app
        uses: tauri-apps/tauri-action@v0
        id: tauri

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
        with:
          tagName: ${{ inputs.release && inputs.version || null }}
          releaseName: ${{ inputs.release && inputs.version || null }}
          releaseBody: "Automated release for ${{ inputs.version }}"
          includeUpdaterJson: true
          releaseDraft: true
          prerelease: true
          includeDebug: ${{ inputs.debug }}
          includeRelease: ${{ !inputs.debug }}


      - name: Add windows portable exe to release
        uses: softprops/action-gh-release@v1
        if: matrix.platform == 'windows-latest' && inputs.release
        with:
          files: |
            ./src-tauri/target/release/Lodestone.exe
            ./src-tauri/target/debug/Lodestone.exe
          tag_name: ${{ inputs.version }}
          draft: true
          prerelease: true

      # on windows, cache installer in src-tauri/target/release/bundle/msi/Lodestone*.msi
      # on windows cache exe in src-tauri/target/release/Lodestone.exe
      # on linux, cache deb in src-tauri/target/release/bundle/deb/lodestone*.deb
      # on linux, cache appimage in src-tauri/target/release/bundle/appimage/lodestone*.AppImage
      # note linux has lowercase l, windows has uppercase L

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}-tauri
          path: "${{ join(fromJson(steps.tauri.outputs.artifactPaths), '\n') }}\n./src-tauri/target/release/Lodestone.exe\n./src-tauri/target/debug/Lodestone.exe"
