name: lodestone-desktop
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      - name: Cache Rust Dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
          key: ${{ runner.os }}-tauri
          shared-key: ${{ runner.os }}-tauri-shared

      - name: Install npm dependencies
        run: npm ci

      - name: Build Tauri desktop app
        uses: tauri-apps/tauri-action@v0

      # on windows, cache installer in src-tauri/target/release/bundle/msi/Lodestone*.msi
      # on windows cache exe in src-tauri/target/release/Lodestone.exe
      # on linux, cache deb in src-tauri/target/release/bundle/deb/lodestone*.deb
      # on linux, cache appimage in src-tauri/target/release/bundle/appimage/lodestone*.AppImage
      # note linux has lowercase l, windows has uppercase L

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}-tauri
          path: |
            ./src-tauri/target/release/bundle/msi/Lodestone*.msi
            ./src-tauri/target/release/Lodestone.exe
            ./src-tauri/target/release/bundle/deb/lodestone*.deb
            ./src-tauri/target/release/bundle/appimage/lodestone*.AppImage
      
