name: Release Candidate Workflow

on:
  push:
    branches:
      - main

jobs:
  build_desktop:
    uses: ./.github/workflows/desktop.yml
    with:
      version: rc
      debug: false
      release: true
    secrets: inherit
