name: Release Candidate Workflow

on:
  push:
    branches:
      - main

jobs:
  lodestone-desktop:
    uses: ./.github/workflows/desktop.yml
    with:
      version: edge
      debug: false
      release: true
    secrets: inherit
