name: Release Workflow

# Developers, to start making a release, tag a commit with vX.Y.Z and push it to main.
# Then this workflow will run and create a draft release with the tag name as the version.
# You can then edit the release to include a changelog and publish it.

on:
  push:
    tags: [ v\d+\.\d+\.\d+ ]

jobs:
  lodestone-desktop:
    uses: ./.github/workflows/desktop.yml
    with:
      version: ${{ github.ref_name }}
      debug: false
      release: true
    secrets: inherit
